### PR TITLE
year bump in all files

### PR DESCRIPTION
**Pull request by sobolevn**
Also added license information to `tests/models.py` and `tests/translations.py`.

### CODE REVIEW

**Comment by sobolevn** [comment]
@neithere any feedback please?

**Comment by jpic** [comment]
Another try ? :golfing_woman:

**Comment by vstoykov** [comment]
This can be rebased and changed to year 2017. I'm not sure though is the project is still alive.

**Comment by neithere** [comment]
Thank you, guys. The project is not dead but I need a free weekend to
complete it's transfer to Jazzband so that it would absorb contributions
more readily without my direct involvement.

Andy

**Comment by justinmayer** [comment]
Hi Andy. Is there any chance you might be able to complete the transfer to Jazzband this weekend? 😅

**Comment by justinmayer** [comment]
Addressed via 27e595a.

**Pull request closed without merging**
