### PR TITLE
Remove support for EOL Python and Django versions

### PR DESCRIPTION
**Pull request by ulgens**
* Removes Python 3.5 - 3.6 support
* Removes Django 1.11 - 2.0 - 2.1 - 3.0 support
* Cleans South related code

### CODE REVIEW

**Comment by justinmayer** [comment]
Hi Ülgen. Thank you for the improvements. I see that you have marked this PR as a draft… Would you please let me know the status? Do you believe it still needs more work?

**Comment by ulgens** [comment]
Hey @justinmayer, sorry for my late response. My plan was to add a pre-commit config with pyupgrade and django-upgrade, but I think that can be a different PR. Also, I think Django 2.2 (EOL) can be removed too, and I will check if I can handle it quickly.

**Comment by ulgens** [comment]
@justinmayer Pushed a commit for removing 2.2. Ready to review.

I can help with updating / merging other PRs after this one 🌷

**Review by justinmayer — APPROVED** [review]
Many thanks for your help with this, Ülgen! 💯 

> I can help with updating / merging other PRs after this one 🌷

That would be wonderful! Which one would you like to focus on first?

**Pull request merged**
