### PR TITLE
Handle timezones for datetime fields

### PR DESCRIPTION
**Pull request by ipmb**
Timezone information is lost when splitting up dates into `year`, `month`, and `day` lookups. This makes sure a timezone aware datetime gets converted to the correct timezone before splitting up to check for duplicate slugs.

### CODE REVIEW

**Comment by ipmb** [comment]
_note_ this includes an unrelated fix for Django 1.10 so the build succeeds
https://docs.djangoproject.com/en/1.10/ref/models/meta/#migrating-from-the-old-api

**Comment by jpic** [comment]
Sharp patch, LGTM, good for rebase and merge

**Comment by justinmayer** [comment]
Hey Peter! Your contribution to `django-autoslug` seems quite useful. Given that compatibility fixes for Django 1.11 and 2.x have already been merged, would you mind rebasing your enhancements on current master so I can merge this pull request?

**Comment by justinmayer** [comment]
Hey Peter. Django-autoslug v1.9.4, which should now support Django 1.10, 1.11, and 2.0+, has been [released](https://github.com/justinmayer/django-autoslug/releases/tag/v1.9.4) and [published to PyPI](https://pypi.org/project/django-autoslug/). I just wanted to let you know in case you wanted to rebase your PR on current master, after which I'd be happy to merge and issue a new release with your enhancement.

Have a great weekend!

**Comment by justinmayer** [comment]
Hi @ipmb. Just thought I would follow up again regarding your contribution. I am adding [AutoPub](https://github.com/autopub/autopub) to this project via #58 in order to auto-publish package releases to PyPI upon pull request merge. To that end, after rebasing on current master, would you please also add a `RELEASE.md` file to this pull request that looks like this:

    Release type: patch
    
    Handle timezones for datetime fields

Many thanks, and happy Sunday!

**Comment by justinmayer** [comment]
Many thanks, Peter, for the original contribution, as well as the follow-up work you did to get it ready for merge + release. Much appreciated!

**Comment by justinmayer** [comment]
@ipmb: Your `django-autoslug` improvements have been released as [v1.9.6](https://github.com/justinmayer/django-autoslug/releases/tag/v1.9.6) by [AutoPub](https://github.com/autopub/autopub). Thanks again for all your efforts!

**Pull request merged**
