### PR TITLE
Fix/empty slug 

### PR DESCRIPTION
**Pull request by mpasternak**
The missing file you requested in PR #18 . Please release this package, my work depends on this bug to be fixed. I've created a fork in the past, ``django-autoslug-iplweb`` and did some work there, but unfortunately it looks like nobody was interested in my branch and we doubled our efforts.

### CODE REVIEW

**Comment by elmcrest** [comment]
+1

**Comment by mpasternak** [comment]
No offense but if you create AutoSlugField from user input, then maybe your use case is not exactly fit for AUTOSlugField, is it?

**Comment by elmcrest** [comment]
might be the case, I'll just explain in short what I do and you and others could decide.

I'm building a document management system which auto-generates kind of a catalogue (`Cabinet`) from meta data about an uploaded document. so f.e. let's say a letter from *Tesla* (`Correspondent`). I use this `label` as an url (so slug) later to render only documents from *Tesla*. Two other fields are `DocumentType` and `CostUnit`.
Now you can image an `url` for a `CabinetView` with f.e. `/tesla/offer/my-new-model-3` so you'd get a filtered list with all documents matching those criteria. of course the example is stupid.

So, maybe a special use case, but I'd say it's exactly what `AutoSlugField` is intended to be used for, though with a unusual source of slugs.

and for the fun of it, a screenshot how I'd "save" this conversation in case I would save it and wanted to find it again in the future ... another stupid example, but also a shameless plug! 😆

Anmerkung 2019-10-25 124056

**Comment by elmcrest** [comment]
but, after more testing, the fix does fix it for ma aswell, sorry that I didn't get this in first place.

so, if I do:

```
>>> co = Correspondent(label="??")
>>> co.save()
>>> co.slug
'correspondent-2'
>>> co = Correspondent(label="???")
>>> co.save()
>>> co.slug
'correspondent-3'
```

I'd still get valid unique slugs - I wasn't thinking about the already existing unique constrain.

I didn't made this up just for the shameless plug joke ... just saying :)

**Comment by elmcrest** [comment]
so, should we delete this discussion to reduce read time of others? ... I could update my first "approval" comment

**Comment by justinmayer** [comment]
[Version 1.9.7 has been released](https://github.com/justinmayer/django-autoslug/releases/tag/v1.9.7), incorporating this fix.

**Pull request closed without merging**
