### PR TITLE
Add license to sdist and wheels

### PR DESCRIPTION
**Pull request by jayvdb**
Also adds run_tests.py to sdist

Closes https://github.com/justinmayer/django-autoslug/issues/55

### CODE REVIEW

**Comment by jayvdb** [comment]
Simple fix for travis is to use xenial for everything; slightly more complicated is fixing the matrix of allowable Django versions.  I'd be interested in fixing that if I can use tox-travis to simplify that process a bit.

**Comment by justinmayer** [comment]
Hi @jayvdb. Very sorry for the delay in following up regarding your pull request. I just fixed the issue with Travis a few moments ago, using Xenial for all jobs. Would you be so kind as to rebase your changes on latest master?

**Comment by justinmayer** [comment]
@jayvdb: I am adding [AutoPub](https://github.com/autopub/autopub) to this project via #58 in order to auto-publish package releases to PyPI upon pull request merge. To that end, after rebasing on current master, please also add a `RELEASE.md` file to this pull request that looks like this:

    Release type: patch
    
    Add license to sdist and wheels

Many thanks, and happy Sunday!

**Comment by jayvdb** [comment]
Will do!  Glad to see the repo is green again.

**Comment by jayvdb** [comment]
@justinmayer , sorry for the delay; that is now done, and green.

**Comment by justinmayer** [comment]
@jayvdb: No apologies necessary. Many thanks for following up and making those changes. Let's see what happens when we push this button. Wheeeee! 🎢

**Comment by jayvdb** [comment]
In case you missed it, all is not well - the deploy phase on master fails https://travis-ci.org/justinmayer/django-autoslug/jobs/564660443

**Comment by justinmayer** [comment]
@jayvdb: Very kind of you to notice and follow up. I was watching the build output when the deploy stage failed and quickly realized the problem: the upload URL for PyPI is not https://pypi.org/ but is instead https://upload.pypi.org/legacy/. So I manually published `django-autoslug` v1.9.5 to PyPI and then [updated the PyPI URL handling in AutoPub](https://github.com/autopub/autopub/commit/e7d9111f31523bc685b9d2560d6ce99cf0ebd358), which will (hopefully) ensure the deploy stage will succeed when the next pull request is merged.

**Pull request merged**
